# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'ViewMonitorExample' do
	pod "ViewMonitor", :path => "../.."
end

target 'ViewMonitorExampleTests' do

end

