# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ViewMonitorObjcExample' do
	pod "ViewMonitor", :path => "../.."
end

target 'ViewMonitorObjcExampleTests' do

end

target 'ViewMonitorObjcExampleUITests' do

end

